apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: popular-slides

build:
  artifacts:
    - image: localhost:32000/popular-slides
      context: web-app

    - image: localhost:32000/popular-slides-spark
      context: spark-app

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
