apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: eat-smart

build:
  artifacts:
    - image: farberg/eat-smart
      context: web-app

    - image: farberg/eat-smart-spark
      context: spark-app

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
