#Begin: Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-deployment-init-configmap
data:
  mysql-init.sql: |
    CREATE TABLE `food` (
      `id` INT NOT NULL,
      `name` VARCHAR(40) NOT NULL,
      `type` VARCHAR(20) NOT NULL,
      `description`  VARCHAR(300) NOT NULL,
      PRIMARY KEY (`id`)
    );

    INSERT INTO food (id, name, type, description) VALUES ('1', 'italian', 'cuisine', 'spaghetti only');
    INSERT INTO food (id, name, type, description) VALUES ('2', 'asian', 'cuisine', 'rice only');
    INSERT INTO food (id, name, type, description) VALUES ('3', 'german', 'cuisine', 'bratwurst only');
    INSERT INTO food (id, name, type, description) VALUES ('4', 'french', 'cuisine', 'baguette only');

    INSERT INTO food (id, name, type, description) VALUES ('21', 'pizza', 'lunch', 'round bread with tomato sauce and cheese');
    INSERT INTO food (id, name, type, description) VALUES ('22', 'rice', 'lunch', 'just rice');
    INSERT INTO food (id, name, type, description) VALUES ('23', 'noodles', 'lunch', 'really long bread');
    INSERT INTO food (id, name, type, description) VALUES ('24', 'tteokbokki', 'lunch', 'rice cakes');

    INSERT INTO food (id, name, type, description) VALUES ('41', 'bread', 'breakfast', 'freshly baked');
    INSERT INTO food (id, name, type, description) VALUES ('42', 'cereals', 'breakfast', 'with milk');
    INSERT INTO food (id, name, type, description) VALUES ('43', 'donuts', 'breakfast', 'with a hole');
    INSERT INTO food (id, name, type, description) VALUES ('44', 'scrambled eggs', 'breakfast', '4 eggs without milk');
    

    CREATE TABLE `smart_cuisine` (
      `cuisine` VARCHAR(50) NOT NULL,
      `avg_gpa` DOUBLE,
      `count` INT NOT NULL,
       PRIMARY KEY (`cuisine`)
    );

    CREATE TABLE `smart_lunch` (
      `lunch` VARCHAR(50) NOT NULL,
      `avg_gpa` DOUBLE,
      `count` INT NOT NULL,
       PRIMARY KEY (`lunch`)
    );

    CREATE TABLE `smart_breakfast` (
      `breakfast` VARCHAR(50) NOT NULL,
      `avg_gpa` DOUBLE,
      `count` INT NOT NULL,
       PRIMARY KEY (`breakfast`)
    );
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: my-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql
  template:
    metadata:
      labels:
        app: my-mysql
    spec:
      # Mount the configmap volume
      # This is an excerpt of deployment.spec.template.spec
      volumes:
        - name: init-volume
          configMap:
            name: mysql-deployment-init-configmap
      containers:
        - name: my-mysql
          image: mysql
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
          # Set required environment variables to initialize the container
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysecretpw"
            - name: MYSQL_DATABASE
              value: "popular"
          ports:
            - containerPort: 33060

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: my-app-mysql-service
spec:
  selector:
    app: my-mysql
  ports:
    - name: mysql-xproto
      protocol: TCP
      port: 33060
      targetPort: 33060
#End: Service
