#Begin: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eat-smart
  labels:
    app: eat-smart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eat-smart-web
  template:
    metadata:
      labels:
        app: eat-smart-web
    spec:
      containers:
        - name: eat-smart-web
          image: farberg/eat-smart
          ports:
            - containerPort: 3000

---
#Begin: Service
kind: Service
apiVersion: v1
metadata:
  name: eat-smart-service
spec:
  selector:
    app: eat-smart-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
#End: Service

---
#Begin: Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eat-smart-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eat-smart-service
                port:
                  number: 3000
